import { Geist, Geist_Mono } from "next/font/google";
import { checkDevice } from "../../lib/device";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "../../components/BootstrapClient";
import { ThemeProvider } from '../../components/Context/ThemeContext'

import "./globals5.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CV",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Lấy headers từ server
  const { userAgent } = await checkDevice()

  return (
    <html lang="en-us" data-useragent={userAgent}>
      <body>
        <ThemeProvider >
          {children}
          <BootstrapClient />
        </ThemeProvider>
      </body>
    </html>

  );
}

